//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProactiveBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class BewerberTable
    {
        public int BewerberID { get; set; }
        public string BeworbeneStelle { get; set; }
        public string Name { get; set; }
        public string Geburtsdatum { get; set; }
        public string Kontaktdaten { get; set; }
        public string Sprachen { get; set; }
        public string Qualifikationen { get; set; }
        public string SozEngagement { get; set; }
        public string Laufbahn { get; set; }
        public string PrivProjekte { get; set; }
    }
}
