//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProactiveBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataConnection : DbContext
    {
        public DataConnection()
            : base("name=DataConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Angestellte> Angestelltes { get; set; }
        public virtual DbSet<BewerberdatenLui> BewerberdatenLuis { get; set; }
        public virtual DbSet<BewerberTable> BewerberTables { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Fachfragen> Fachfragens { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FAQFragen> FAQFragens { get; set; }
        public virtual DbSet<GespeicherteBewerber> GespeicherteBewerbers { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Stellen> Stellens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    }
}
