//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProactiveBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQFragen
    {
        public int FAQFragenID { get; set; }
        public string FAQFrageDU { get; set; }
        public string FAQFrageSie { get; set; }
    }
}
