//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProactiveBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class GespeicherteBewerber
    {
        public int BewerberID { get; set; }
        public Nullable<int> Job { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string PostalCode { get; set; }
        public string Place { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string Career { get; set; }
        public string EducationalBackground { get; set; }
        public string ProgrammingLanguage { get; set; }
        public string SocialEngagement { get; set; }
        public string Language { get; set; }
        public string PrivateProjects { get; set; }
        public string Newsletter { get; set; }
    }
}
