//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProactiveBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stellen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stellen()
        {
            this.BewerberdatenLuis = new HashSet<BewerberdatenLui>();
        }
    
        public int StellenID { get; set; }
        public string Stellenname { get; set; }
        public string Profil { get; set; }
        public string Aufgaben { get; set; }
        public string Gehalt { get; set; }
        public string Einstellungsdatum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BewerberdatenLui> BewerberdatenLuis { get; set; }
    }
}
